### ISSUE TITLE
Wetting loop

### ISSUE THREAD

**Issue by ShallowClover** [zippity21/Stardew_Valley_Regression_Mod#91]
I believe it *might* be triggered by wetting around an npc who would have an interaction, but doesn't because they are a child other than Jas and Vinnie? Because all three times it's happened have been around other child npcs.

**Comment by valeriemaximoff** [comment]
This also happened to me today when I was talking to Trinnie from RSV, so so far that's holding true. Below is he portion of the log that kept repeating over and over.

`[20:40:56 ERROR Age Regression] This mod failed in the GameLoop.OneSecondUpdateTicking event. Technical details: 
IndexOutOfRangeException: Index was outside the bounds of the array.
   at PrimevalTitmouse.Animations.HandleVillager(Body b, Boolean mess, Boolean inUnderwear, Boolean overflow, Boolean attempt, Int32 baseFriendshipLoss, Int32 radius) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Animations.cs:line 359
   at PrimevalTitmouse.Body.StartWetting(Boolean voluntary, Boolean inUnderwear) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Body.cs:line 538
   at PrimevalTitmouse.Body.Wet(Boolean voluntary, Boolean inUnderwear) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Body.cs:line 616
   at PrimevalTitmouse.Body.AddBladder(Single amount) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Body.cs:line 133
   at PrimevalTitmouse.Body.AddWater(Single amount, Single conversionRatio) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Body.cs:line 225
   at PrimevalTitmouse.Body.HandleTime(Single hours) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Body.cs:line 705
   at PrimevalTitmouse.Regression.ReceiveUpdateTick(Object sender, OneSecondUpdateTickingEventArgs e) in C:\Users\Mark Duda\source\repos\Stardew_Valley_Regression_Mod\Regression\PrimevalTitmouse\Regression.cs:line 135
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101`
